name: Run Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
    contents: read
    checks: write
    id-token: write

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Install GCC 14
        run: |
          sudo apt update
          sudo apt install -y gcc-14 g++-14

      - name: ⚙️ Configure CMake
        env:
          CC: gcc-14
          CXX: g++-14
        run: cmake -S . -B build

      - name: 🧪 Build & Run unit tests
        run: |
          cmake --build build --target unit-test --parallel $(nproc)
          ./build/test/unit/test.out -r junit -o results.xml

      - name: 📊 Build & Run rower calibration tests
        run: |
          environments=$(grep -oP '^\[env:\K(?!.*(?:debug|custom|dynamic)).*(?=\])' < "platformio.ini")
          for environment in $(echo "${environments}" | cut -d'-' -f1 | sort -u); do
            ${{github.workspace}}/build/test/calibration/run-calibration "${environment}-generic"
          done

      - name: 📋 Test summary
        uses: test-summary/action@v2
        with:
          paths: "results.xml"
        if: always()
